//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmployeeApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class ASP_API
    {
        public int ID { get; set; }
        public string FirstName { get; set; }
        public string Middle { get; set; }
        public string LastName { get; set; }
        public Nullable<System.DateTime> DoB { get; set; }
        public Nullable<bool> Gender { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
    }
}
